CREATE TABLE monitoramento_solo (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_leitura TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    umidade NUMBER(5,2),
    temperatura NUMBER(5,2),
    ph NUMBER(4,2),
    nitrogenio NUMBER(5,2),
    fosforo NUMBER(5,2),
    potassio NUMBER(5,2)
);

-- Utilize dados inseridos manualmente para testar conexão com o banco e tratativas de situações criticas

-- INSERT INTO monitoramento_solo (umidade, temperatura, ph, nitrogenio, fosforo, potassio)
-- VALUES (65.3, 22.8, 6.9, 14.5, 7.2, 12.1);